version: 2
jobs:
  openscad-mxe-32bit:
    working_directory: ~/workspace
    docker:
      - image: openscad/mxe-i686-gui:latest
    steps:
      - checkout
      - run:
          name: Build OpenSCAD Windows Application (32bit)
          no_output_timeout: 18000
          command: |
              export NUMCPU=2
              export MXEDIR=/mxe
              export LIB3MF_INCLUDEDIR=/mxe/usr/i686-w64-mingw32.static.posix/include/lib3mf
              export LIB3MF_LIBDIR=/mxe/usr/i686-w64-mingw32.static.posix/lib
              if [ x"${CIRCLE_BRANCH}" = xmaster ]; then export SUFFIX=""; else export SUFFIX="_$(echo ${CIRCLE_BRANCH} | sed -e 's,pull/,PR,')"; fi
              export OPENSCAD_VERSION="$(date +%Y.%m.%d).ci${CIRCLE_BUILD_NUM}"
              ./scripts/release-common.sh -snapshot -mingw32 -v "$OPENSCAD_VERSION"
              mkdir -p /tmp/out
              for f in mingw*/*.zip mingw*/*.exe; do N=$(basename "$f" | sed -e "s/\\(-x86-[36][24]\\)/\\1${SUFFIX}/;"); cp -iv "$f" /tmp/out/"$N"; done
              if [ -n "${CODE_SIGNING_KEY}" ]; then
                  cd /tmp/out
                  echo $CODE_SIGNING_DATA | base64 -d | gzip -d | gpg --import --allow-secret-key-import --pinentry-mode loopback --passphrase-file <(echo $CODE_SIGNING_PW)
                  export GPG_ARGS="--batch --yes --passphrase-fd 0 --pinentry-mode loopback --detach-sign --armor"
                  for a in *.exe *.zip; do echo "$CODE_SIGNING_PW" | gpg -u "$CODE_SIGNING_KEY" $GPG_ARGS "$a"; sha256sum "$a" | tee "${a}.sha256"; sha512sum "$a" | tee "${a}.sha512"; done
                  rm -rf ~/.gnupg
              else
                  echo "Skipping code signing."
              fi
      - store_artifacts:
          path: /tmp/out
          destination: 32-bit
  openscad-mxe-64bit:
    working_directory: ~/workspace
    docker:
      - image: openscad/mxe-x86_64-gui:latest
    steps:
      - checkout
      - run:
          name: Build OpenSCAD Windows Application (64bit)
          no_output_timeout: 18000
          command: |
              export NUMCPU=2
              export MXEDIR=/mxe
              export LIB3MF_INCLUDEDIR=/mxe/usr/x86_64-w64-mingw32.static.posix/include/lib3mf
              export LIB3MF_LIBDIR=/mxe/usr/x86_64-w64-mingw32.static.posix/lib
              if [ x"${CIRCLE_BRANCH}" = xmaster ]; then export SUFFIX=""; else export SUFFIX="_$(echo ${CIRCLE_BRANCH} | sed -e 's,pull/,PR,')"; fi
              export OPENSCAD_VERSION="$(date +%Y.%m.%d).ci${CIRCLE_BUILD_NUM}"
              ./scripts/release-common.sh -snapshot -mingw64 -v "$OPENSCAD_VERSION"
              mkdir -p /tmp/out
              for f in mingw*/*.zip mingw*/*.exe; do N=$(basename "$f" | sed -e "s/\\(-x86-[36][24]\\)/\\1${SUFFIX}/;"); cp -iv "$f" /tmp/out/"$N"; done
              if [ -n "${CODE_SIGNING_KEY}" ]; then
                  cd /tmp/out
                  echo $CODE_SIGNING_DATA | base64 -d | gzip -d | gpg --import --allow-secret-key-import --pinentry-mode loopback --passphrase-file <(echo $CODE_SIGNING_PW)
                  export GPG_ARGS="--batch --yes --passphrase-fd 0 --pinentry-mode loopback --detach-sign --armor"
                  for a in *.exe *.zip; do echo "$CODE_SIGNING_PW" | gpg -u "$CODE_SIGNING_KEY" $GPG_ARGS "$a"; sha256sum "$a" | tee "${a}.sha256"; sha512sum "$a" | tee "${a}.sha512"; done
                  rm -rf ~/.gnupg
              else
                  echo "Skipping code signing."
              fi
      - store_artifacts:
          path: /tmp/out
          destination: 64-bit
  openscad-appimage-64bit:
    working_directory: ~/workspace
    docker:
      - image: openscad/appimage-x86_64-base:latest
    steps:
      - checkout
      - run:
          name: Build OpenSCAD AppImage (64bit)
          no_output_timeout: 18000
          command: |
              set +e
              . /opt/qt5*/bin/qt5*-env.sh
              set -e
              export OPENSCAD_COMMIT=$(git log -1 --pretty=format:%h)
              export OPENSCAD_VERSION="$(date +%Y.%m.%d).ai${CIRCLE_BUILD_NUM}"
              if [ x"${CIRCLE_BRANCH}" = xmaster ]; then export SUFFIX=""; else export SUFFIX="_$(echo ${CIRCLE_BRANCH} | sed -e 's,pull/,PR,')"; fi
              git submodule update --init
              mkdir build && cd build
              cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DEXPERIMENTAL=ON -DSNAPSHOT=ON -DOPENSCAD_VERSION="$OPENSCAD_VERSION" -DOPENSCAD_COMMIT="$OPENSCAD_COMMIT"
              make -j2
              make install DESTDIR=../AppDir
              cd ..
              export PATH=/appimage/usr/bin:"$PATH"
              export EXTRA_QT_PLUGINS=svg
              VERSION="$OPENSCAD_VERSION" linuxdeploy --plugin qt --output appimage --appdir AppDir
              mkdir -p /tmp/out
              for f in OpenSCAD-*.AppImage; do N=$(basename "$f" | sed -e "s/OpenSCAD-\\(.*\\)/OpenSCAD-${OPENSCAD_VERSION}-${SUFFIX}\\1/;"); cp -iv "$f" /tmp/out/"$N"; done
              if [ -n "${CODE_SIGNING_KEY}" ]; then
                  cd /tmp/out
                  echo $CODE_SIGNING_DATA | base64 -d | gzip -d | gpg --import --allow-secret-key-import --pinentry-mode loopback --passphrase-file <(echo $CODE_SIGNING_PW)
                  export GPG_ARGS="--batch --yes --passphrase-fd 0 --pinentry-mode loopback --detach-sign --armor"
                  for a in *.AppImage; do echo "$CODE_SIGNING_PW" | gpg -u "$CODE_SIGNING_KEY" $GPG_ARGS "$a"; sha256sum "$a" | tee "${a}.sha256"; sha512sum "$a" | tee "${a}.sha512"; done
                  rm -rf ~/.gnupg
              else
                  echo "Skipping code signing."
              fi
      - store_artifacts:
          path: /tmp/out
          destination: 64-bit
  openscad-macos:
    macos:
      xcode: 12.2.0
    steps:
      - checkout
      - run:
          name: Build OpenSCAD MacOS
          no_output_timeout: 18000
          command: |
              system_profiler SPHardwareDataType SPSoftwareDataType SPStorageDataType SPDeveloperToolsDataType
              export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
              echo "PATH = $PATH"
              export COLUMNS=80 # needed by some macports tool
              MACPORTS_SHA512=396b457e698848a4e56902162dc8ceee6d71c4d520fa57d2387e9d52363390fffe33a2d0a6e690bd90e9131d036d06db642891beff23eb5956b501423cf8d29f
              MACPORTS_CACHE_SHA512=8236594a3c3d0f4c0b0c96f8a7ffbe0d5773a3b78fca148f40b2c2be2463eec41e0635ffe61337de154b2b5301c3f7d51edb654d37a3092cf2401d7ca94150e8
              LIBRARIES_CACHE_SHA512=95192c6bc2cbbe8d4c1dfafdda4febd7bc9061c5722b21ab7ac5a32072746745f18e9553e26f9bf5141a71d32bddf0a2b7ea61bfd655827b9ed61f2cd4c29887
              CI_BASEDIR=/Users/distiller/project
              export OPENSCAD_LIBRARIES=/Users/distiller/libraries/install
              MACPORTS=MacPorts-2.7.1
              MACPORTS_CACHE=macports-circleci.tar.bz2
              LIBRARIES_CACHE=libraries-circleci.tar.bz2
              mkdir /tmp/out
              mkdir -p "$OPENSCAD_LIBRARIES"
              ( echo "Loading macports cache..." ; cd /tmp && curl -f -s -S --insecure -O https://files.openscad.org/ci-cache/"$MACPORTS_CACHE" ) || true
              ( echo "Loading libraries cache..." ; cd /tmp && curl -f -s -S --insecure -O https://files.openscad.org/ci-cache/"$LIBRARIES_CACHE" ) || true
              sudo mkdir -p /opt/local
              sudo tar xj -C /opt/local -f /tmp/"$MACPORTS_CACHE" || true
              if [ -f /opt/local/bin/port ]; then
                  MACPORTS_CACHE_FILE_SHA512="$(shasum -a 512 /tmp/"$MACPORTS_CACHE" | cut -d ' ' -f 1)"
                  if [ "$MACPORTS_CACHE_FILE_SHA512" != "$MACPORTS_CACHE_SHA512" ]; then
                      echo "Failed to match sha512 for $MACPORTS_CACHE"
                      echo "Expected: $MACPORTS_CACHE_SHA512"
                      echo "Actual:   $MACPORTS_CACHE_FILE_SHA512"
                      exit 1
                  fi
                  if [ -f /tmp/"$LIBRARIES_CACHE" ]; then
                      tar xj -C "$OPENSCAD_LIBRARIES" -f /tmp/"$LIBRARIES_CACHE" || true
                      LIBRARIES_CACHE_FILE_SHA512="$(shasum -a 512 /tmp/"$LIBRARIES_CACHE" | cut -d ' ' -f 1)"
                      if [ "$LIBRARIES_CACHE_FILE_SHA512" != "$LIBRARIES_CACHE_SHA512" ]; then
                          echo "Failed to match sha512 for $LIBRARIES_CACHE"
                          echo "Expected: $LIBRARIES_CACHE_SHA512"
                          echo "Actual:   $LIBRARIES_CACHE_FILE_SHA512"
                          exit 1
                      fi
                  fi
                  echo "Start building dependencies: $(date)"
                  export PKG_CONFIG_PATH="$OPENSCAD_LIBRARIES/lib/pkgconfig"
                  export DYLD_LIBRARY_PATH="$OPENSCAD_LIBRARIES/lib"
                  export DYLD_FRAMEWORK_PATH="$OPENSCAD_LIBRARIES/lib"
                  echo "DYLD_LIBRARY_PATH: $DYLD_LIBRARY_PATH"
                  export PATH=$OPENSCAD_LIBRARIES/bin:$PATH
                  ./scripts/macosx-build-dependencies.sh double_conversion
                  ./scripts/macosx-build-dependencies.sh eigen
                  ./scripts/macosx-build-dependencies.sh gmp
                  ./scripts/macosx-build-dependencies.sh mpfr
                  ./scripts/macosx-build-dependencies.sh glew
                  ./scripts/macosx-build-dependencies.sh gettext
                  ./scripts/macosx-build-dependencies.sh libffi
                  ./scripts/macosx-build-dependencies.sh freetype
                  ./scripts/macosx-build-dependencies.sh ragel
                  ./scripts/macosx-build-dependencies.sh harfbuzz
                  ./scripts/macosx-build-dependencies.sh libzip
                  ./scripts/macosx-build-dependencies.sh libxml2
                  ./scripts/macosx-build-dependencies.sh fontconfig || true
                  ./scripts/macosx-build-dependencies.sh hidapi
                  ./scripts/macosx-build-dependencies.sh libuuid
                  ./scripts/macosx-build-dependencies.sh lib3mf
                  ./scripts/macosx-build-dependencies.sh poppler
                  ./scripts/macosx-build-dependencies.sh pixman
                  ./scripts/macosx-build-dependencies.sh cairo
                  ./scripts/macosx-build-dependencies.sh glib2
                  ./scripts/macosx-build-dependencies.sh boost
                  ./scripts/macosx-build-dependencies.sh cgal
                  ./scripts/macosx-build-dependencies.sh qt5
                  ./scripts/macosx-build-dependencies.sh opencsg
                  ./scripts/macosx-build-dependencies.sh qscintilla
                  ./scripts/macosx-build-dependencies.sh -d sparkle
                  tar cj -C "$OPENSCAD_LIBRARIES" -f /tmp/out/"$LIBRARIES_CACHE" .
                  shasum -a 512 /tmp/out/"$LIBRARIES_CACHE" > /tmp/out/"$LIBRARIES_CACHE".sha512
                  export GMP_DIR="$OPENSCAD_LIBRARIES"
                  export MPFR_DIR="$OPENSCAD_LIBRARIES"
                  echo "Start building OpenSCAD: $(date)"
                  export NUMCPU=4
                  time ./scripts/release-common.sh -snapshot
                  cd build
                  OPENSCAD_NAME=$(ls OpenSCAD-*.dmg)
                  shasum -a 256 "$OPENSCAD_NAME" > "$OPENSCAD_NAME".sha256
                  shasum -a 512 "$OPENSCAD_NAME" > "$OPENSCAD_NAME".sha512
                  cp -v "$OPENSCAD_NAME"* /tmp/out/
                  echo "Finished building OpenSCAD: $(date)"
              else
                  echo "MacPorts not found, installing $MACPORTS"
                  MACPORTSFILE="$MACPORTS".tar.bz2
                  curl -s -S --insecure -O https://distfiles.macports.org/MacPorts/"$MACPORTSFILE"
                  if [ "$(shasum -a 512 "$MACPORTSFILE" | cut -d ' ' -f 1)" != "$MACPORTS_SHA512" ]; then
                      echo "Failed to match sha512 for $MACPORTSFILE"
                      echo "Expected: $MACPORTS_SHA512"
                      echo "Actual:   $(shasum -a 512 "$MACPORTSFILE")"
                      exit 1
                  fi
                  tar xjf "$MACPORTSFILE"
                  cd "$MACPORTS"
                  ./configure
                  make
                  sudo make install
                  sudo port -d selfupdate
                  sudo port -N install cmake curl pkgconfig autoconf automake libtool python39
                  sudo port select --set python python39
                  sudo port select --set python3 python39
                  tar cj -C /opt/local -f /tmp/out/"$MACPORTS_CACHE" .
                  shasum -a 512 /tmp/out/"$MACPORTS_CACHE"
              fi
      - store_artifacts:
          path: /tmp/out
          destination: build

workflows:
  version: 2
  master-build:
    jobs:
      - openscad-mxe-32bit:
          context: secret-context
          filters:
              branches:
                  only:
                      - master
      - openscad-mxe-64bit:
          context: secret-context
          filters:
              branches:
                  only:
                      - master
      - openscad-appimage-64bit:
          context: secret-context
          filters:
              branches:
                  only:
                      - master
  branch-build:
    jobs:
      - openscad-mxe-32bit:
          filters:
              branches:
                  ignore:
                      - master
                      - coverity_scan
                      - /^(?i:continuous)$/
      - openscad-mxe-64bit:
          filters:
              branches:
                  ignore:
                      - master
                      - coverity_scan
                      - /^(?i:continuous)$/
      - openscad-appimage-64bit:
          filters:
              branches:
                  ignore:
                      - master
                      - coverity_scan
                      - /^(?i:continuous)$/
      - openscad-macos:
          filters:
              branches:
                  only:
                      - /.*-macos/
  scheduled:
    triggers:
      - schedule:
          cron: "30 6 * * 0,1,3,5,6"
          filters:
              branches:
                  only:
                      - master
    jobs:
      - openscad-macos
