name: CGAL Versions

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        cgal-version: [5.2]
        fast-csg-available: [true]
        include:
          - os: ubuntu-20.04
            cgal-version: 5.1
            fast-csg-available: true
          - os: ubuntu-20.04
            cgal-version: 4.11
            fast-csg-available: false

    runs-on: ${{ matrix.os }}

    name: "CGAL ${{ matrix.cgal-version }} (fast-csg: ${{ matrix.fast-csg-available }})"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: CGAL_VERSION=${{ matrix.cgal-version }} ./scripts/travis-ci-before-install-linux.sh bionic
    - name: Dependency fixup
      run: sudo apt-get install qt5-default gettext gcovr
    - name: Build and test
      run: FAST_CSG_AVAILABLE=${{ matrix.fast-csg-available }} ./scripts/github-ci.sh build test coverage
    - name: Upload Test Result Report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Test Result Report - CGAL ${{ matrix.cgal-version }} - fast-csg=${{ matrix.fast-csg-available }}
        path: b/tests/Testing/Temporary/*_report.html

