name: Legacy CGAL

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - cgal-version: 4.11
            fast-csg-available: false
        include:
          - cgal-version: 5.1
            fast-csg-available: true
        include:
          - cgal-version: 5.2
            fast-csg-available: true
        include:
          - cgal-version: 5.2.x
            fast-csg-available: true

    runs-on: ubuntu-18.04

    name: CGAL ${{ matrix.cgal-version }} (fast-csg: ${{ matrix.fast-csg-available }})

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: CGAL_VERSION=${{ matrix.cgal-version }} ./scripts/travis-ci-before-install-linux.sh bionic
    - name: Dependency fixup
      run: sudo apt-get install qt5-default gettext gcovr
    - name: Build and test
      run: FAST_CSG_AVAILABLE=${{ matrix.fast-csg-available }} ./scripts/github-ci.sh build test coverage
    - name: Upload Test Result Report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Test Result Report - CGAL 4.x (no fast-csg)
        path: b/tests/Testing/Temporary/*_report.html

